// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/11/2025, 00:10:30
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/kirap/Desktop/Site/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/plugins/**/*.{js,ts,mjs}","C:/Users/kirap/Desktop/Site/app/composables/**/*.{js,ts,mjs}","C:/Users/kirap/Desktop/Site/app/utils/**/*.{js,ts,mjs}","C:/Users/kirap/Desktop/Site/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/Desktop/Site/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;