
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AboutBluePrintSection: typeof import("../app/components/About/BluePrintSection.vue")['default']
export const AboutHeroAboutSection: typeof import("../app/components/About/HeroAboutSection.vue")['default']
export const AboutIntro: typeof import("../app/components/About/Intro.vue")['default']
export const AboutPilaresSection: typeof import("../app/components/About/PilaresSection.vue")['default']
export const AboutSloganSection: typeof import("../app/components/About/SloganSection.vue")['default']
export const AboutTriadeSection: typeof import("../app/components/About/TriadeSection.vue")['default']
export const AboutCtaSection: typeof import("../app/components/About/ctaSection.vue")['default']
export const ContactHeroSection: typeof import("../app/components/Contact/HeroSection.vue")['default']
export const ContactMapSection: typeof import("../app/components/Contact/MapSection.vue")['default']
export const IndexAboutSection: typeof import("../app/components/Index/AboutSection.vue")['default']
export const IndexHeroSection: typeof import("../app/components/Index/HeroSection.vue")['default']
export const IndexSectoresSection: typeof import("../app/components/Index/SectoresSection.vue")['default']
export const IndexServicesSection: typeof import("../app/components/Index/ServicesSection.vue")['default']
export const IndexStatusSection: typeof import("../app/components/Index/StatusSection.vue")['default']
export const IndexCtaSection: typeof import("../app/components/Index/ctaSection.vue")['default']
export const ServicesHeroSection: typeof import("../app/components/Services/HeroSection.vue")['default']
export const ServicesSection: typeof import("../app/components/Services/ServicesSection.vue")['default']
export const ServicesCtaSection: typeof import("../app/components/Services/ctaSection.vue")['default']
export const ElementosFooter: typeof import("../app/components/elementos/Footer.vue")['default']
export const ElementosHeader: typeof import("../app/components/elementos/Header.vue")['default']
export const IndustriesHeroSection: typeof import("../app/components/industries/HeroSection.vue")['default']
export const IndustriesSection: typeof import("../app/components/industries/Section.vue")['default']
export const IndustriesCtaSection: typeof import("../app/components/industries/ctaSection.vue")['default']
export const ScriptGoogleMapsDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.d.vue")['default']
export const ScriptGoogleMaps: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue")['default']
export const ScriptGoogleMapsAdvancedMarkerElementDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.d.vue")['default']
export const ScriptGoogleMapsAdvancedMarkerElement: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue")['default']
export const ScriptGoogleMapsCircleDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.d.vue")['default']
export const ScriptGoogleMapsCircle: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue")['default']
export const ScriptGoogleMapsHeatmapLayerDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.d.vue")['default']
export const ScriptGoogleMapsHeatmapLayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue")['default']
export const ScriptGoogleMapsInfoWindowDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.d.vue")['default']
export const ScriptGoogleMapsInfoWindow: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue")['default']
export const ScriptGoogleMapsMarkerDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.d.vue")['default']
export const ScriptGoogleMapsMarker: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue")['default']
export const ScriptGoogleMapsMarkerClustererDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.d.vue")['default']
export const ScriptGoogleMapsMarkerClusterer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue")['default']
export const ScriptGoogleMapsPinElementDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.d.vue")['default']
export const ScriptGoogleMapsPinElement: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue")['default']
export const ScriptGoogleMapsPolygonDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.d.vue")['default']
export const ScriptGoogleMapsPolygon: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue")['default']
export const ScriptGoogleMapsPolylineDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.d.vue")['default']
export const ScriptGoogleMapsPolyline: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue")['default']
export const ScriptGoogleMapsRectangleDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.d.vue")['default']
export const ScriptGoogleMapsRectangle: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue")['default']
export const ScriptAriaLoadingIndicatorDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.d.vue")['default']
export const ScriptAriaLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']
export const ScriptCarbonAdsDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.d.vue")['default']
export const ScriptCarbonAds: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']
export const ScriptCrispDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.d.vue")['default']
export const ScriptCrisp: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']
export const ScriptGoogleAdsenseDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.d.vue")['default']
export const ScriptGoogleAdsense: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']
export const ScriptIntercomDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.d.vue")['default']
export const ScriptIntercom: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']
export const ScriptLemonSqueezyDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.d.vue")['default']
export const ScriptLemonSqueezy: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']
export const ScriptLoadingIndicatorDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.d.vue")['default']
export const ScriptLoadingIndicator: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const ScriptPayPalButtonsDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.d.vue")['default']
export const ScriptPayPalButtons: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue")['default']
export const ScriptPayPalMarksDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.d.vue")['default']
export const ScriptPayPalMarks: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue")['default']
export const ScriptPayPalMessagesDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.d.vue")['default']
export const ScriptPayPalMessages: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue")['default']
export const ScriptStripePricingTableDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.d.vue")['default']
export const ScriptStripePricingTable: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const ScriptVimeoPlayerDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.d.vue")['default']
export const ScriptVimeoPlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const ScriptYouTubePlayerDVue: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.d.vue")['default']
export const ScriptYouTubePlayer: typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAboutBluePrintSection: LazyComponent<typeof import("../app/components/About/BluePrintSection.vue")['default']>
export const LazyAboutHeroAboutSection: LazyComponent<typeof import("../app/components/About/HeroAboutSection.vue")['default']>
export const LazyAboutIntro: LazyComponent<typeof import("../app/components/About/Intro.vue")['default']>
export const LazyAboutPilaresSection: LazyComponent<typeof import("../app/components/About/PilaresSection.vue")['default']>
export const LazyAboutSloganSection: LazyComponent<typeof import("../app/components/About/SloganSection.vue")['default']>
export const LazyAboutTriadeSection: LazyComponent<typeof import("../app/components/About/TriadeSection.vue")['default']>
export const LazyAboutCtaSection: LazyComponent<typeof import("../app/components/About/ctaSection.vue")['default']>
export const LazyContactHeroSection: LazyComponent<typeof import("../app/components/Contact/HeroSection.vue")['default']>
export const LazyContactMapSection: LazyComponent<typeof import("../app/components/Contact/MapSection.vue")['default']>
export const LazyIndexAboutSection: LazyComponent<typeof import("../app/components/Index/AboutSection.vue")['default']>
export const LazyIndexHeroSection: LazyComponent<typeof import("../app/components/Index/HeroSection.vue")['default']>
export const LazyIndexSectoresSection: LazyComponent<typeof import("../app/components/Index/SectoresSection.vue")['default']>
export const LazyIndexServicesSection: LazyComponent<typeof import("../app/components/Index/ServicesSection.vue")['default']>
export const LazyIndexStatusSection: LazyComponent<typeof import("../app/components/Index/StatusSection.vue")['default']>
export const LazyIndexCtaSection: LazyComponent<typeof import("../app/components/Index/ctaSection.vue")['default']>
export const LazyServicesHeroSection: LazyComponent<typeof import("../app/components/Services/HeroSection.vue")['default']>
export const LazyServicesSection: LazyComponent<typeof import("../app/components/Services/ServicesSection.vue")['default']>
export const LazyServicesCtaSection: LazyComponent<typeof import("../app/components/Services/ctaSection.vue")['default']>
export const LazyElementosFooter: LazyComponent<typeof import("../app/components/elementos/Footer.vue")['default']>
export const LazyElementosHeader: LazyComponent<typeof import("../app/components/elementos/Header.vue")['default']>
export const LazyIndustriesHeroSection: LazyComponent<typeof import("../app/components/industries/HeroSection.vue")['default']>
export const LazyIndustriesSection: LazyComponent<typeof import("../app/components/industries/Section.vue")['default']>
export const LazyIndustriesCtaSection: LazyComponent<typeof import("../app/components/industries/ctaSection.vue")['default']>
export const LazyScriptGoogleMapsDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.d.vue")['default']>
export const LazyScriptGoogleMaps: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMaps.vue")['default']>
export const LazyScriptGoogleMapsAdvancedMarkerElementDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.d.vue")['default']>
export const LazyScriptGoogleMapsAdvancedMarkerElement: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsAdvancedMarkerElement.vue")['default']>
export const LazyScriptGoogleMapsCircleDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.d.vue")['default']>
export const LazyScriptGoogleMapsCircle: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsCircle.vue")['default']>
export const LazyScriptGoogleMapsHeatmapLayerDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.d.vue")['default']>
export const LazyScriptGoogleMapsHeatmapLayer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsHeatmapLayer.vue")['default']>
export const LazyScriptGoogleMapsInfoWindowDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.d.vue")['default']>
export const LazyScriptGoogleMapsInfoWindow: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsInfoWindow.vue")['default']>
export const LazyScriptGoogleMapsMarkerDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.d.vue")['default']>
export const LazyScriptGoogleMapsMarker: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue")['default']>
export const LazyScriptGoogleMapsMarkerClustererDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.d.vue")['default']>
export const LazyScriptGoogleMapsMarkerClusterer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue")['default']>
export const LazyScriptGoogleMapsPinElementDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.d.vue")['default']>
export const LazyScriptGoogleMapsPinElement: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPinElement.vue")['default']>
export const LazyScriptGoogleMapsPolygonDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.d.vue")['default']>
export const LazyScriptGoogleMapsPolygon: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolygon.vue")['default']>
export const LazyScriptGoogleMapsPolylineDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.d.vue")['default']>
export const LazyScriptGoogleMapsPolyline: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsPolyline.vue")['default']>
export const LazyScriptGoogleMapsRectangleDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.d.vue")['default']>
export const LazyScriptGoogleMapsRectangle: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/GoogleMaps/ScriptGoogleMapsRectangle.vue")['default']>
export const LazyScriptAriaLoadingIndicatorDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.d.vue")['default']>
export const LazyScriptAriaLoadingIndicator: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptAriaLoadingIndicator.vue")['default']>
export const LazyScriptCarbonAdsDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.d.vue")['default']>
export const LazyScriptCarbonAds: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue")['default']>
export const LazyScriptCrispDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.d.vue")['default']>
export const LazyScriptCrisp: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue")['default']>
export const LazyScriptGoogleAdsenseDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.d.vue")['default']>
export const LazyScriptGoogleAdsense: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue")['default']>
export const LazyScriptIntercomDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.d.vue")['default']>
export const LazyScriptIntercom: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue")['default']>
export const LazyScriptLemonSqueezyDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.d.vue")['default']>
export const LazyScriptLemonSqueezy: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue")['default']>
export const LazyScriptLoadingIndicatorDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.d.vue")['default']>
export const LazyScriptLoadingIndicator: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']>
export const LazyScriptPayPalButtonsDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.d.vue")['default']>
export const LazyScriptPayPalButtons: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalButtons.vue")['default']>
export const LazyScriptPayPalMarksDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.d.vue")['default']>
export const LazyScriptPayPalMarks: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMarks.vue")['default']>
export const LazyScriptPayPalMessagesDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.d.vue")['default']>
export const LazyScriptPayPalMessages: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptPayPalMessages.vue")['default']>
export const LazyScriptStripePricingTableDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.d.vue")['default']>
export const LazyScriptStripePricingTable: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']>
export const LazyScriptVimeoPlayerDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.d.vue")['default']>
export const LazyScriptVimeoPlayer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']>
export const LazyScriptYouTubePlayerDVue: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.d.vue")['default']>
export const LazyScriptYouTubePlayer: LazyComponent<typeof import("../node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
